/*
You are given two strings, str1 and str2, of lengths n and m, respectively.

A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".



Example 1:

Input: str1 = "TFTF", str2 = "ab"

Output: "ababa"

Explanation:

The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.

Return "ababa" since it is the lexicographically smaller string.

Example 2:

Input: str1 = "TFTF", str2 = "abc"

Output: ""

Explanation:

No string that satisfies the conditions can be generated.

Example 3:

Input: str1 = "F", str2 = "d"

Output: "a"



Constraints:

1 <= n == str1.length <= 104
1 <= m == str2.length <= 500
str1 consists only of 'T' or 'F'.
str2 consists only of lowercase English characters.
*/

class Solution {
    public String generateString(String str1, String str2) {
        char[] chars1 = str1.toCharArray();
        int n = chars1.length;
        int m = str2.length();
        char[] result = new char[n + m - 1];
        Arrays.fill(result, '?');

        int[] zArr = calcZ(str2);
        int lastT = -m;
        for (int i = 0; i < n; i++) {
            if (chars1[i] != 'T') {
                continue;
            }
            int overlap = Math.max(lastT + m - i, 0);
            if (overlap > 0 && zArr[m - overlap] < overlap) {
                return "";
            }
            for (int j = overlap; j < m; j++) {
                result[i + j] = str2.charAt(j);
            }
            lastT = i;
        }

        int[] lastUnknown = new int[result.length];
        int prevQ = -1;
        for (int i = 0; i < result.length; i++) {
            if (result[i] == '?') {
                result[i] = 'a';
                prevQ = i;
            }
            lastUnknown[i] = prevQ;
        }

        zArr = calcZ(str2 + new String(result));

        for (int i = 0; i < n; i++) {
            if (chars1[i] != 'F') {
                continue;
            }
            if (zArr[m + i] < m) {
                continue;
            }
            int pos = lastUnknown[i + m - 1];
            if (pos < i) {
                return "";
            }
            result[pos] = 'b';
            i = pos;
        }

        return new String(result);
    }

    private int[] calcZ(String str) {
        char[] chars = str.toCharArray();
        int n = chars.length;
        int[] z = new int[n];
        int left = 0;
        int right = 0;
        for (int i = 1; i < n; i++) {
            if (i <= right) {
                z[i] = Math.min(z[i - left], right - i + 1);
            }
            while (i + z[i] < n && chars[z[i]] == chars[i + z[i]]) {
                left = i;
                right = i + z[i];
                z[i]++;
            }
        }
        z[0] = n;
        return z;
    }
}